services:
  - type: web
    name: face-attendance-system
    env: python
    buildCommand: |
      apt-get update && 
      apt-get install -y cmake build-essential libopenblas-dev liblapack-dev libx11-dev && 
      pip install --upgrade pip && 
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
